%\VignetteIndexEntry{Strings and Ranges Practical}
%\VignettePackage{GeneticsHTSCourse}
%\VignetteEngine{knitr::knitr}

% To compile this document
% library('knitr'); rm(list=ls()); knit('DESeq2.Rnw')

\documentclass[12pt]{article}
\usepackage{wasysym,marvosym}
\newcommand{\usecase}{\textit{\textbf{Use Case: }}}
\newcommand{\exercise}{\textit{\textbf{Exercise: }}}
\newcommand{\notebell}{\bell}
\newcommand{\noteright}{\Pointinghand}
\newcommand{\textinfo}{\Info}
<<knitr, echo=TRUE, results="hide",echo=FALSE>>=
library("knitr")
opts_chunk$set(tidy=FALSE,dev="png",
               fig.width=8,fig.height=4.5,
               message=FALSE,eval=TRUE,echo=TRUE)
@ 

<<style, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\usepackage{ifthen} 
\newboolean{includethis} 
\setboolean{includethis}{true} 
\newcommand{\ifinclude}[1]{\ifthenelse{\boolean{includethis}}{#1}{}} 

\title{Exercises}

\author{Mark Dunning}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}


\maketitle


\tableofcontents

\section{Plotting basics}

\subsection{Weather Data}

\exercise Read the ozone data into your Rstudio. Practice using the 'file.choose' to locate the file on your hard drive

<<echo=TRUE,eval=FALSE>>=
myfile <- file.choose()
ozone <- read.csv(myfile)
@

\exercise Verify that the dimensions and first few lines are as we expect. HINT: use the \Rfunction{dim} and \Rfunction{head} functions.


<<echo=FALSE>>=
ozone <- read.csv("data/ozone.csv")
@

<<>>=
dim(ozone)
head(ozone)
@



\exercise Make a Scatter Plot of the temperature variable

<<echo=FALSE>>=
plot(ozone$Temp)
@

\subsection{Birth Rate data}

\exercise Data describing birth rates of males and females are given in the file 'UKBirthRate.tsv'. What function do you think you would use to read these data? Using your chosen function, read these data into RStudio and check the dimensions.

<<>>=
births <- read.delim("data/UKBirthRate.tsv")
dim(births)
head(births)
@
HINT: You should get 243 columns and 4 rows.

\exercise Plot how the Male birth rate changes over the years

<<>>=
plot(births$Age, births$Male.babies)
@


\exercise Plot the difference between Male and Female birth rate

<<>>=
plot(births$Male.babies, births$Female.babies)
@




\subsection{Chick weight data}

\exercise: Load the in-built dataset `chickwts`

<<>>=
data(chickwts)
head(chickwts)
@


\exercise: Visualise the difference in weight of chicks that were fed with different diets

<<>>=
boxplot(chickwts$weight ~ chickwts$feed)
stripchart(chickwts$weight ~ chickwts$feed,vertical = TRUE,add=TRUE)
@


\exercise: Overlay the individual points and try and jitter

<<>>=
boxplot(chickwts$weight ~ chickwts$feed)
stripchart(chickwts$weight ~ chickwts$feed,vertical = TRUE,add=TRUE)
@

\subsection{A.B.M data}

\exercise Read the ABM data using the commands you have seen so far

<<>>=
abm <- read.csv("data//ABM.csv")
@

\exercise Make a barplot of the race of each subject

<<>>=
barplot(table(abm$race))
@

How many categories do you see

<<>>=
abm <- read.csv("data//ABM.csv",na.strings=".")
@

Now, re-try the barplot

<<>>=
barplot(table(abm$race))
@

\exercise Make a histogram of the years

\exercise cross-tabulate the race and gender


\section{Plot options}

\subsection{Birth rate date}

\exercise Read the UK birth rate data and plot the male and female birth rates on the same x axis. Choose different colours for male and female. 

<<>>=
births <- read.delim("data/UKBirthRate.tsv")
plot(births$Age, births$Male.babies, col="red",pch=15,xlab="Year", ylab="Birth Rate",main="Comparison of male and female birth rates")
points(births$Age, births$Female.babies,col="blue",pch=14, ylab="Birth Rate")
@

\exercise Add a legend in the top-left corner

<<eval=FALSE>>=
legend("topleft", legend=c("Male", "Female"), col=c("red","blue"),pch=c(15,14))
@

\exercise We decide that we are only interested in the 20th century (years 1900 to 2000). Modify your axis accordingly and repeat the plot

<<>>=
plot(births$Age, births$Male.babies, col="red",pch=15,xlab="Year", ylab="Birth Rate",xlim=c(1900,2000))
points(births$Age, births$Female.babies,col="blue",pch=14, ylab="Birth Rate")

@


\subsection{Weather data}

\exercise Read the Weather data back into R. Produce a boxplot with the temperature on the y axis, and month on the x axis.

<<>>=
ozone <- read.csv("data/ozone.csv")
boxplot(ozone$Temp ~ ozone$Month)
@

\exercise Repeat the plot with a different colour for each box. First create a vector with five valid colour names (i.e. the name appears in the output of \Rfunction{colours()}) and use this as the col argument to \Rfunction{plot}.

<<>>=
boxplot(ozone$Temp ~ ozone$Month,col=c("Red", "Orange", "Yellow", "Green","Blue"))
@

\exercise Now, load the \Rpackage{RColorBrewer} package and see what palettes are available using \Rfunction{display.brewer.all()}. Create a palette of length 5 from one of the available options and use this palette to colour the boxplot.

<<>>=
library(RColorBrewer)
mypal <- brewer.pal(5, "Set1")
boxplot(ozone$Temp ~ ozone$Month,col=mypal)
@

We will now re-visit the scatter plot of Ozone level and Temperature

<<>>=
plot(ozone$Temp,ozone$Ozone,pch=16)
@

Lets consider the steps required to colour each point according to the month that the observations were made. Our goal is to produce a vector of length \Sexpr{nrow(ozone)}, where each item in the vector is the colour to be used to plot the corresponding point.

Step 1: Using the table function on the Month variable, you will see how many observations are present for each month

<<>>=
table(ozone$Month)
@

\exercise Create a vector of the string red repeated 31 times and assign it to a variable. HINT Use the \Rfunction{rep} for this task.

<<>>=
vec1 <- rep("red", 31)
@

\exercise Repeat the same exercise to create colour vectors of the appropriate length for all the other months

<<>>=
vec2 <- rep("orange", 30)
vec3 <- rep("yellow", 31)
vec4 <- rep("green", 31)
vec5 <- rep("blue", 30)
@

\exercise Now combine all your vectors together and use this as the col argument when creating the scatter plot. Check that the length of your combined vector is \Sexpr{nrow(ozone)}.

<<>>=
cols <- c(vec1,vec2,vec3,vec4,vec5)
length(cols)
plot(ozone$Temp,ozone$Ozone,pch=16,col=cols)
@

In R, there are usually multiple ways of completing the same task. 

\exercise One can use the \Rfunction{rep} function in a different manner. This time we can use the times argument


<<>>=
cols2 <- rep(mypal, times = table(ozone$Month))
plot(ozone$Temp,ozone$Ozone,pch=16,col=cols2)
@

\section{Data Manipulation}

\subsection{Calculating new variables}

<<>>=
library(survival)
sdata <- read.delim("data/Two groups.txt")
Time <- sdata$Days.elapsed
@

<<>>=
Group <- rep("Control", nrow(sdata))
Group[which(is.na(sdata$Control))] <- "Treated"
@


<<>>=
Event <- sdata$Control
Event[which(is.na(Event))] <- sdata$Treated[which(is.na(Event))]
@


<<>>=
SurvData <- Surv(Time,Event)
plot(survfit(SurvData ~ Group))
@


Return to the birth rate data

\exercise Read the birth rate data into R

<<>>=
births <- read.delim("data/UKBirthRate.tsv")
@


\exercise Create a subset of the data that contains just the years 1900 - 2000.

<<>>=
centdata <- births[births$Age > 1900 & births$Age < 2001,]
@

\exercise Create a new variable that captures the decade

<<>>=
decade <- substr(centdata$Age, 3, 3)
@


\exercise Create a boxplot that shows the increase in Female birth rates for each decade

<<>>=
boxplot(centdata$Female.babies ~ decade,col="mistyrose")
@

\exercise Add boxes to show the increase in Male birth rate over the same period

<<>>=
boxplot(centdata$Female.babies ~ decade,col="mistyrose")
boxplot(centdata$Male.babies ~ decade,col="steelblue",add=TRUE)
@



\subsection{Combining data from multiple files}

In this section we will consider the published data from the NKI breast cancer series

http://ccb.nki.nl/data/

<<>>=
emat <- read.delim("data/NKI295.exprs.txt",stringsAsFactors=FALSE)
fmat <- read.delim("data/NKI295.fdata.txt")
pmat <- read.delim("data/NKI295.pdata.txt")
@

<<>>=
dim(emat)
dim(pmat)
@

<<>>=
colnames(emat)[1:10]
pmat[1:10,1]
@

<<>>=
emat[1:10,1]
fmat[1:10,]
@

\subsection{Subsetting the patients}

\exercise Find the sample names of the ER negative patients. You will first need to identify which column in the phenotypic data holds the ER status of each patient.

<<>>=

which(pmat$ER == "Negative")

erNegSamples <- pmat$sampleNames[which(pmat$ER == "Negative")]
@

\exercise Now match these sample names to the columns in the expression matrix

<<>>=
erNegMatix <- emat[,match(erNegSamples, colnames(emat))]

@


\subsection{Retrieving the data for a particular gene}

\exercise Find the probe ID that corresponds to the gene symbol "ESR1"

<<>>=

grep("ESR1", fmat$symbol)
fmat$probeID[grep("ESR1", fmat$symbol)]
@

\exercise Match the probe ID that you just found to relevant row in the expression matrix

<<>>=
match("18904", emat[,1])

erVals <- emat[18889,-1]
@

\subsection{Correlate gene expression with clinical variables}

\exercise Take the gene expression values for ESR1, and 

<<>>=
boxplot(as.numeric(erVals) ~ pmat$ER)
@



\end{document}
