%\VignetteIndexEntry{Strings and Ranges Practical}
%\VignettePackage{GeneticsHTSCourse}
%\VignetteEngine{knitr::knitr}

% To compile this document
% library('knitr'); rm(list=ls()); knit('DESeq2.Rnw')

\documentclass[12pt]{article}
\usepackage{wasysym,marvosym}
\newcommand{\usecase}{\textit{\textbf{Use Case: }}}
\newcommand{\exercise}{\textit{\textbf{Exercise: }}}
\newcommand{\notebell}{\bell}
\newcommand{\noteright}{\Pointinghand}
\newcommand{\textinfo}{\Info}
<<knitr, echo=FALSE, results="hide">>=
library("knitr")
opts_chunk$set(tidy=FALSE,dev="png",fig.show="hide",
               fig.width=4,fig.height=4.5,
               message=FALSE,eval=F)
@ 

<<style, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\usepackage{ifthen} 
\newboolean{includethis} 
\setboolean{includethis}{true} 
\newcommand{\ifinclude}[1]{\ifthenelse{\boolean{includethis}}{#1}{}} 

\title{Exercises}

\author{Mark Dunning}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}


\maketitle


\tableofcontents

\section{Plotting basics}

\subsection{Weather Data}

\exercise Read the ozone data into your Rstudio. You will find this in the data folder

<<>>=
ozone <- read.csv("data/ozone.csv")
dim(ozone)
head(ozone)
@



\exercise Make a Scatter Plot of the temperature variable

<<>>=
plot(ozone$Temp)

@

\subsection{Birth Rate data}

\exercise Data describing birth rates of males and females are given in the file 'UKBirthRate.tsv'. What function do you think you would use to read these data? Using your chosen function, read these data into RStudio and check the dimensions.

<<>>=
births <- read.delim("data/UKBirthRate.tsv")
dim(births)
head(births)
@
HINT: You should get 243 columns and 4 rows.

\exercise Plot how the Male birth rate changes over the years

<<>>=
plot(births$Age, births$Male.babies)
@


\exercise Plot the difference between Male and Female birth rate

<<>>=
plot(births$Male.babies, births$Female.babies)
@

\subsection{A.B.M data}

\exercise Read the ABM data using the commands you have seen so far

<<>>=
abm <- read.csv("data//ABM.csv")
@

\exercise Make a barplot of the race of each subject

<<>>=
barplot(table(abm$race))
@

How many categories do you see

<<>>=
abm <- read.csv("data//ABM.csv",na.strings=".")
@

Now, re-try the barplot

<<>>=
barplot(table(abm$race))
@

\exercise Make a histogram of the years

\exercise cross-tabulate the race and gender


\subsection{Liver data}

http://faculty.washington.edu/heagerty/Books/Biostatistics/DATA/liverdoc.txt

<<>>=
liver <- read.delim("http://faculty.wshington.edu/heagerty/Books/Biostatistics/DATA/liver.txt")

@


\subsection{Chick weight data}

\exercise: Load the in-built dataset `chickwts`

<<>>=
data(chickwts)
head(chickwts)
@


\exercise: Visualise the difference in weight of chicks that were fed with different diets

<<>>=
boxplot(chickwts$weight ~ chickwts$feed)
@

\exercise: Overlay the individual points and try and jitter

<<>>=
stripchart(chickwts$weight ~ chickwts$feed)
@


\end{document}
